openapi: 3.0.0
info:
  title: Sample Requests - TBC Checkout Web Payments
  version: 1.0.0
servers:
  - url: https://{{env}}
components:
  schemas:
    PaymentAmount:
      type: object
      required:
        - currency
        - total
      properties:
        currency:
          type: string
          enum: [GEL, USD, EUR]
        total:
          type: number
        subTotal:
          type: number
        tax:
          type: number
        shipping:
          type: number
    PaymentResponse:
      type: object
      required:
        - payId
        - status
        - links
      properties:
        payId:
          type: string
        status:
          type: string
          enum: [Created, Processing, Succeeded, Failed]
        links:
          type: array
          items:
            type: object
            required:
              - uri
              - method
              - rel
            properties:
              uri:
                type: string
              method:
                type: string
                enum: [GET, POST, REDIRECT]
              rel:
                type: string
                enum: [self, approval_url]
        transactionId:
          type: string
          nullable: true
        httpStatusCode:
          type: integer
        developerMessage:
          type: string
          nullable: true
        userMessage:
          type: string
          nullable: true
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /v1/tpay/access-token:
    post:
      tags:
        - default
      summary: web-get-token
      description: >-
        **_Path_**

        /access-token



        **_Description_**

        Request access-token that should then be used to access Tpay resourses. 



        **_Request Parameters_**


        Name | Type | Description

        ------------ | ------------- | ------------

        **apikey** * _(header)_ | _string_ | developer app key value

        **client\_id** * _(body)_ | _string_ | tpay client_id (merchant id) 

        **client\_secret** * _(body)_ | _string_ | client secret



        **_Response Model_**


        Name | Type | Description

        ------------ | ------------- | ------------

        **access_token** | _string_ | access token value

        **token_type** | _string_ | type of the token is set to “Bearer”

        **expires_in** | _integer($int32)_ | lifetime in seconds of the access
        token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - client_id
                - client_secret
              properties:
                client_id:
                  type: string
                  description: TBC Checkout client_id (merchant id)
                  example: '{{web-client-id}}'
                client_secret:
                  type: string
                  description: TBC Checkout client_secret
                  example: '{{web-client-secret}}'
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
        - name: apikey
          in: header
          schema:
            type: string
          description: 'Developer app key for making API calls through Open API platfrom. '
          example: '{{app-key}}'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Fri, 09 Aug 2019 13:57:47 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=2592000
            Set-Cookie:
              schema:
                type: string
                example: >-
                  TS0109cf5a=01863392edcef5cd69cc283fb1b09f88d0689295837666f8c80c069f75f6d1c96bcc8cfee5df7b497cac007ea2fa588c1a0f780b9f;
                  Path=/; Domain=.tst1openapi.tbcbank.ge
          content:
            application/json:
              schema:
                type: object
                required:
                  - access_token
                  - token_type
                  - expires_in
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: integer
              example:
                access_token: >-
                  eyJhbGciOiJSUzI1NiIsImtpZCI6IjNDQkQzN0Q1Qjc2QTcyMTMzNTFFMTYzMDk1NDkyRjE4MTA3RkE1MEYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJQTDAzMWJkcWNoTTFIaFl3bFVrdkdCQl9wUTgifQ.eyJuYmYiOjE1NjUzNTkwNjcsImV4cCI6MTU2NTQ0NTQ2NywiaXNzIjoiaHR0cHM6Ly9hY2NvdW50c3RwYXl0c3QudGJjYmFuay5nZS8iLCJhdWQiOlsiaHR0cHM6Ly9hY2NvdW50c3RwYXl0c3QudGJjYmFuay5nZS9yZXNvdXJjZXMiLCJwYXltZW50YXBpIl0sImNsaWVudF9pZCI6IjUzOTk5OTkiLCJzY29wZSI6WyJwYXltZW50YXBpIl19.EG29V9wxjGPUpnJlYOcAcEYw9BvSiCFwqfzAbZ4jkxJD4q-EcP94-i7XLZhzS8Vv4k1NBWHg2x7MKQQu81AlBFungVCKFwNCV0ItkYPTSguq4s5QGpgQcSjtmC_q6wVTT8WA4jR7IcwQ8qZMKKcrAZJBehDWdal1uO_Mhnn1Dnc9KFdFnXWUc7iIjIryuHPc3U-ZOQh2COIl0Acl-LTMeRh_KZByz2Gf2lLShhRbI0G-5YtWXObtLZ2ZKfCJB50TtaMM16vrfSQXh0FX6BHHxAtyPBflOzCgovi8CORgkTbaGaPtJHqjfep8r8L-45zhFVPXT19rLhWyfhEPBDm78A
                expires_in: 86400
                token_type: Bearer
  /v1/tpay/payments:
    post:
      tags:
        - default
      summary: web-create-payment
      description: >-
        **_Path_**

        /payments



        **_Description_**

        Request initiates Tpay web payment. The response contains payment object
        details and links for a) checking payment status and b) redirecting user
        to finish initiated payment.



        **_Authorization_**


        Bearer {_access-token value_}


        **_Request Parameters_**



        Name | Type | Description

        ------------ | ------------- | ------------

        **apikey** * _(header)_ | _string_ | developer app key value

        **amount {}** * _(body)_ | _array_ | payment amount {}

        **-- currency** * | _string_ | currency of transaction

        **-- total** * | _number_ | total amount of payment

        **-- subtotal** | _number_ | amount of purchase

        **-- tax** | _number_ | amount of tax

        **-- shipping** | _number_ | amount of shipping price

        **returnurl** * _(body)_ | _string_ | callback url to redirect user
        after finishing payment (e.g."order details page")

        **extra** _(body)_ | _string_ | additional parameter for
        merchant-specific info



        **_Response Model_**



        Name | Type | Description

        ------------ | ------------- | ------------

        **payId** | _string_ | payment id 

        **status** | _string_ | payment status / Created / Processing /
        Succeeded / Failed

        **links {}** | _array_ | links

        **-- uri** | _string_ | URL

        **-- method** | _string_ | method to use on URL

        **-- rel** | _string_ | action to use on URL

        **transactionId** | _string_ | transaction_id from UFC

        **httpStatusCode** | _string_ | http status code

        **developerMessage** | _string_ | developer message for logging in local
        system

        **userMessage** | _string_ | error message for user




        >_httpStatusCode_ values:

        * 200 - finished successfully

        * 400 - bad request, incorrect parameters

        * 401 - request unauthorized

        * 500 - internal server error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - amount
                - returnurl
              properties:
                amount:
                  $ref: '#/components/schemas/PaymentAmount'
                returnurl:
                  type: string
                extra:
                  type: string
                userIpAddress:
                  type: string
                expirationMinutes:
                  type: string
                callbackUrl:
                  type: string
                merchantPaymentId:
                  type: string
                saveCardToDate:
                  type: string
                language:
                  type: string
                  enum: [EN, KA]
                methods:
                  type: array
                  items:
                    type: integer
                installmentProducts:
                  type: array
                  items:
                    type: object
                    properties:
                      Name:
                        type: string
                      Price:
                        type: number
                      Quantity:
                        type: integer
                preAuth:
                  type: boolean
                saveCard:
                  type: boolean
            example:
              amount:
                currency: GEL
                total: 200
                subTotal: 0
                tax: 0
                shipping: 0
              returnurl: shopping.ge/callback
              extra: GE60TB7226145063300008
              userIpAddress: 127.0.0.1
              expirationMinutes: "5"
              methods: [5, 7, 8]
              installmentProducts:
                - Name: t1
                  Price: 100
                  Quantity: 1
                - Name: t1
                  Price: 50
                  Quantity: 1
                - Name: t1
                  Price: 50
                  Quantity: 1
              callbackUrl: https://google.com
              preAuth: true
              language: EN
              merchantPaymentId: P123123
              saveCard: true
              saveCardToDate: "0321"
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{app-key}}'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Mon, 12 Aug 2019 07:59:49 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=2592000
            Set-Cookie:
              schema:
                type: string
                example: >-
                  TS0109cf5a=01863392ed7b7bab11dc91a2d5f051521d5303c0a1190db78a2bb48539dfede940b09b4243bdfd3ed1535b75885c62fc7bdd11b52e;
                  Path=/; Domain=.tst1openapi.tbcbank.ge
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
              example:
                payId: tpay-fkgokd18839
                status: Created
                links:
                  - uri: >-
                      https://tpaypaymentapi.test.loc:8079/v1/Payments/tpay-fkgokd18839
                    method: GET
                    rel: self
                  - uri: >-
                      https://tpaycheckoutweb.test.loc:8078/checkout/tpay-fkgokd18839
                    method: REDIRECT
                    rel: approval_url
                transactionId: null
                httpStatusCode: 200
                developerMessage: null
                userMessage: null
  /v1/tpay/payments/{payment_id}:
    get:
      tags:
        - default
      summary: web-get-payment
      description: >-
        **_Path_**

        /payments/{payment_id}



        **_Description_**

        Request returns payment details for given payment_id



        **_Authorization_**


        Bearer {_access-token value_}


        **_Request Parameters_**



        Name | Type | Description

        ------------ | ------------- | ------------

        **apikey** * _(header)_ | _string_ | developer app key value

        **payment_id** * _(path)_ | _string_ | payment id



        **_Response Model_**



        Name | Type | Description

        ------------ | ------------- | ------------

        **payId** | _string_ | payment id 

        **status** | _string_ | payment status / Created / Processing /
        Succeeded / Failed

        **links {}** | _array_ | links

        **-- uri** | _string_ | URL

        **-- method** | _string_ | method to use on URL

        **-- rel** | _string_ | action to use on URL

        **transactionId** | _string_ | transaction_id from UFC

        **httpStatusCode** | _string_ | http status code

        **developerMessage** | _string_ | developer message for logging in local
        system

        **userMessage** | _string_ | error message for user




        >_httpStatusCode_ values:

        * 200 - finished successfully

        * 400 - bad request, incorrect parameters

        * 401 - request unauthorized

        * 500 - internal server error
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{app-key}}'
        - name: payment_id
          in: path
          schema:
            type: string
          required: true
          example: '{{payment-id}}'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Mon, 12 Aug 2019 08:20:01 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=2592000
            Set-Cookie:
              schema:
                type: string
                example: >-
                  TS0109cf5a=01863392edad24cf9335207ca252ffe183c1a4910db1cd2e7672ad6783e1818d6f744dac94eda1006f9767ec3df79d2fd7afccb06c;
                  Path=/; Domain=.tst1openapi.tbcbank.ge
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
              example:
                payId: tpay-fkgokd18839
                status: Created
                links: null
                transactionId: null
                httpStatusCode: 200
                developerMessage: null
                userMessage: null
  /v1/tpay/payments/{payment_id}/cancel:
    post:
      tags:
        - default
      summary: web-cancel-payment
      description: >-
        **_Path_**

        /payments



        **_Description_**

        Request initiates Tpay web payment. The response contains payment object
        details and links for a) checking payment status and b) redirecting user
        to finish initiated payment.



        **_Authorization_**


        Bearer {_access-token value_}


        **_Request Parameters_**



        Name | Type | Description

        ------------ | ------------- | ------------

        **apikey** * _(header)_ | _string_ | developer app key value

        **amount {}** * _(body)_ | _array_ | payment amount {}

        **-- currency** * | _string_ | currency of transaction

        **-- total** * | _number_ | total amount of payment

        **-- subtotal** | _number_ | amount of purchase

        **-- tax** | _number_ | amount of tax

        **-- shipping** | _number_ | amount of shipping price

        **returnurl** * _(body)_ | _string_ | callback url to redirect user
        after finishing payment (e.g."order details page")

        **extra** _(body)_ | _string_ | additional parameter for
        merchant-specific info



        **_Response Model_**



        Name | Type | Description

        ------------ | ------------- | ------------

        **payId** | _string_ | payment id 

        **status** | _string_ | payment status / Created / Processing /
        Succeeded / Failed

        **links {}** | _array_ | links

        **-- uri** | _string_ | URL

        **-- method** | _string_ | method to use on URL

        **-- rel** | _string_ | action to use on URL

        **transactionId** | _string_ | transaction_id from UFC

        **httpStatusCode** | _string_ | http status code

        **developerMessage** | _string_ | developer message for logging in local
        system

        **userMessage** | _string_ | error message for user




        >_httpStatusCode_ values:

        * 200 - finished successfully

        * 400 - bad request, incorrect parameters

        * 401 - request unauthorized

        * 500 - internal server error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - amount
              properties:
                amount:
                  type: number
            example:
              amount: 2
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{app-key}}'
        - name: payment_id
          in: path
          schema:
            type: string
          required: true
          example: '{{payment-id}}'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Mon, 12 Aug 2019 07:59:49 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=2592000
            Set-Cookie:
              schema:
                type: string
                example: >-
                  TS0109cf5a=01863392ed7b7bab11dc91a2d5f051521d5303c0a1190db78a2bb48539dfede940b09b4243bdfd3ed1535b75885c62fc7bdd11b52e;
                  Path=/; Domain=.tst1openapi.tbcbank.ge
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
              example:
                payId: tpay-fkgokd18839
                status: Created
                links:
                  - uri: >-
                      https://tpaypaymentapi.test.loc:8079/v1/Payments/tpay-fkgokd18839
                    method: GET
                    rel: self
                  - uri: >-
                      https://tpaycheckoutweb.test.loc:8078/checkout/tpay-fkgokd18839
                    method: REDIRECT
                    rel: approval_url
                transactionId: null
                httpStatusCode: 200
                developerMessage: null
                userMessage: null
  /v1/tpay/payments/{payment_id}/completion:
    post:
      tags:
        - default
      summary: web-complete-payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - amount
              properties:
                amount:
                  type: number
            example:
              amount: 0.1
      security:
        - bearerAuth: []
      parameters:
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{app-key}}'
        - name: payment_id
          in: path
          schema:
            type: string
          required: true
          example: '{{payment-id}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'